FROM alpine:latest AS build
# We would be fine using 4.7.5 (latest) except for needing
# https://github.com/plougher/squashfs-tools/commit/a044577948aa09e6f10ce5cf95292f8971ac66b9 and
# https://github.com/plougher/squashfs-tools/commit/52992df017ea9f80e37012947538249547a0d048
# to fix https://github.com/edera-dev/protect/issues/3655
# There is a build failure with `XZ_SUPPORT = 0` in some later revision.
ARG SQUASHFS_TOOLS_VERSION=52992df017ea9f80e37012947538249547a0d048
WORKDIR /usr/src

# build dependencies
RUN apk update && apk add build-base cmake git sed zstd-dev zstd-static

# check out squashfs-tools sources
WORKDIR /usr/src
ENV SQUASHFS_TOOLS_VERSION=${SQUASHFS_TOOLS_VERSION}
RUN git clone https://github.com/plougher/squashfs-tools && cd squashfs-tools && git checkout $SQUASHFS_TOOLS_VERSION
WORKDIR /usr/src/squashfs-tools/squashfs-tools
# We don't use most of these libs, so turn them off.
RUN sed -i \
    -e 's/COMP_DEFAULT = gzip/COMP_DEFAULT = zstd/' \
    -e 's/GZIP_SUPPORT = 1/GZIP_SUPPORT = 0/' \
    -e 's/LZO_SUPPORT = 1/LZO_SUPPORT = 0/' \
    -e 's/XZ_SUPPORT = 1/XZ_SUPPORT = 0/' \
    -e 's/LZ4_SUPPORT = 1/LZ4_SUPPORT = 0/' \
    -e 's/USE_PREBUILT_MANPAGES = n/USE_PREBUILT_MANPAGES = y/' \
    Makefile
ENV CFLAGS="-O2 -Wall -static"
ENV LDFLAGS="-static"

RUN make -j`nproc` && make install INSTALL_DIR=/usr/obj/usr/bin

## copy final squashfs-tools into a scratch image
FROM scratch AS final
COPY --from=build /usr/obj/ /
